# Copyright 2023-2025 The MathWorks, Inc.

# To specify which MATLAB release to install in the container, edit the value of the MATLAB_RELEASE argument.
# Use uppercase to specify the release, for example: ARG MATLAB_RELEASE=R2021b
ARG MATLAB_RELEASE=R2023a

# Specify the extra products to install into the image. These products can either be toolboxes or support packages.
ARG ADDITIONAL_PRODUCTS="Image_Processing_Toolbox Mapping_Toolbox Signal_Processing_Toolbox Statistics_and_Machine_Learning_Toolbox Curve_Fitting_Toolbox Parallel_Computing_Toolbox Robotics_System_Toolbox"

# Specify the fonts packages to install into the image. The default value below installs fonts for ja_JP-UTF-8 locales support.
ARG FONTS_PACKAGES="fonts-vlgothic ibus-mozc"

# Specify the extra Ubuntu APT packages to install into the image.
ARG ADDITIONAL_APT_PACKAGES="git build-essential cmake ninja-build libvtk9-dev python3 python3-venv python3-pip libglu1-mesa libxrender1 libxext6 libsm6" 

# ARG OPENCARP_BINARY=opencarp-v18.1.deb
# ARG OPENCARP_DL_LINK=https://git.opencarp.org/api/v4/projects/16/packages/generic/opencarp-linux/v18.1/${OPENCARP_BINARY}
ARG PARAVIEW_DL_LINK="https://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v6.1&type=binary&os=Linux&downloadFile=ParaView-6.1.0-MPI-Linux-Python3.12-x86_64.tar.gz"
ARG HOST_UID=1000
ARG HOST_GID=1000
# This Dockerfile builds on the Ubuntu-based mathworks/matlab image.
# To check the available matlab images, see: https://hub.docker.com/r/mathworks/matlab
FROM mathworks/matlab:$MATLAB_RELEASE

# Declare the global argument to use at the current build stage
ARG MATLAB_RELEASE
ARG ADDITIONAL_PRODUCTS
ARG FONTS_PACKAGES
ARG ADDITIONAL_APT_PACKAGES
# ARG OPENCARP_BINARY
# ARG OPENCARP_DL_LINK
ARG PARAVIEW_DL_LINK
ARG HOST_UID=1000
ARG HOST_GID=1000

ENV CONDA_DIR=/home/matlab/miniconda3
ENV PARAVIEW_DIR=/home/matlab/paraview
ENV PATH=${CONDA_DIR}/bin:${CONDA_DIR}/condabin:${PARAVIEW_DIR}/bin:$PATH
ENV CONDA_PLUGINS_AUTO_ACCEPT_TOS=true

# By default, the MATLAB container runs as user "matlab". To install mpm dependencies, switch to root.
USER root

# Install mpm dependencies
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install --yes \
        wget \
        ca-certificates \
        ${FONTS_PACKAGES} \
        ${ADDITIONAL_APT_PACKAGES} \
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

#download e installazione opencarp
# RUN wget -q ${OPENCARP_DL_LINK} \
#     && apt-get clean && apt-get update \
#     && apt-get install -y ./${OPENCARP_BINARY} \
#     && rm ${OPENCARP_BINARY} \
#     && rm -rf /var/lib/apt/lists/*
    
# Run mpm to install MathWorks products into the existing MATLAB installation directory,
# and delete the mpm installation afterwards.
# Modify it by setting the ADDITIONAL_PRODUCTS defined above,
# e.g. ADDITIONAL_PRODUCTS="Statistics_and_Machine_Learning_Toolbox Parallel_Computing_Toolbox MATLAB_Coder".
# If mpm fails to install successfully then output the logfile to the terminal, otherwise cleanup.

# allineamento uid user con macchina host
RUN userdel ubuntu && \
    usermod -u ${HOST_UID} matlab && \
    groupmod -g ${HOST_GID} matlab && \
    find /home/matlab -user 1001 -exec chown -h ${HOST_UID} {} \; 2>/dev/null || true

# Switch to user matlab, and pass in $HOME variable to mpm,
# so that mpm can set the correct root folder for the support packages.
WORKDIR /tmp
USER matlab
RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm \
    && chmod +x mpm \
    && EXISTING_MATLAB_LOCATION=$(dirname $(dirname $(readlink -f $(which matlab)))) \
    && sudo HOME=${HOME} ./mpm install \
        --destination=${EXISTING_MATLAB_LOCATION} \
        --release=${MATLAB_RELEASE} \
        --products ${ADDITIONAL_PRODUCTS} \
    || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false) \
    && sudo rm -rf mpm /tmp/mathworks_root.log

# Install cobiveco and dependencies from forked repository
WORKDIR /home/matlab
RUN git clone -b digitaltwin2-cobiveco-ldrb --single-branch https://github.com/FedeOmb/Cobiveco.git /home/matlab/cobiveco

WORKDIR /home/matlab/cobiveco/dependencies
RUN chmod +x install_cobiveco_docker.sh && bash install_cobiveco_docker.sh

WORKDIR /home/matlab
#download paraview e link pvpython
RUN mkdir -p ${PARAVIEW_DIR} \
    && wget -O /tmp/paraview.tar.gz ${PARAVIEW_DL_LINK}  \
    && tar -xzf /tmp/paraview.tar.gz -C ${PARAVIEW_DIR} --strip-components=1 \
    && rm /tmp/paraview.tar.gz

#install miniconda and create a virtual environment for cobiveco

RUN wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
        -O /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -b -p ${CONDA_DIR} \
    && rm /tmp/miniconda.sh \
    && ${CONDA_DIR}/bin/conda init bash \
    && ${CONDA_DIR}/bin/conda config --add channels conda-forge \
    && ${CONDA_DIR}/bin/conda env create -f /home/matlab/cobiveco/requirements.txt -n cobiveco -y \
    && ${CONDA_DIR}/bin/conda clean -afy

#patch conda path in code
RUN sed -i \
    "s|condaPath = '/home/federico/miniconda3/condabin/conda'|condaPath = '${CONDA_DIR}/condabin/conda'|g" \
    /home/matlab/cobiveco/functions/createBoundarySurfacesAB.m

# When running the container a license file can be mounted,
# or a license server can be provided as an environment variable.
# For more information, see https://hub.docker.com/r/mathworks/matlab

# Alternatively, you can provide a license server to use
# with the docker image while building the image.
# Specify the host and port of the machine that serves the network licenses
# if you want to bind in the license info as an environment variable.
# You can also build with something like --build-arg LICENSE_SERVER=27000@MyServerName,
# in which case you should uncomment the following two lines.
# If these lines are uncommented, $LICENSE_SERVER must be a valid license
# server or browser mode will not start successfully.
# ARG LICENSE_SERVER
# ENV MLM_LICENSE_FILE=$LICENSE_SERVER

# The following environment variables allow MathWorks to understand how this MathWorks
# product is being used. This information helps us make MATLAB even better.
# Your content, and information about the content within your files, is not shared with MathWorks.
# To opt out of this service, delete the environment variables defined in the following line.
# See the Help Make MATLAB Even Better section in the accompanying README to learn more:
# https://github.com/mathworks-ref-arch/matlab-dockerfile#help-make-matlab-even-better
#ENV MW_DDUX_FORCE_ENABLE=true MW_CONTEXT_TAGS=$MW_CONTEXT_TAGS,MATLAB:TOOLBOXES:DOCKERFILE:V1

WORKDIR /home/matlab
# Inherit ENTRYPOINT and CMD from base image.
